# Generated by Django 3.2.3 on 2021-05-28 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('date', models.CharField(blank=2, max_length=150)),
                ('img', models.ImageField(upload_to='')),
                ('description', models.TextField()),
            ],
        ),
    ]
