# Generated by Django 3.2.3 on 2021-05-24 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Butcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('mobile', models.BigIntegerField()),
                ('city', models.CharField(max_length=64)),
                ('town', models.CharField(default='', max_length=120)),
                ('experience', models.CharField(max_length=64)),
                ('speciality', models.CharField(max_length=64)),
                ('time', models.CharField(max_length=64)),
                ('price', models.CharField(max_length=64)),
                ('heard', models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=64)),
                ('mobile', models.BigIntegerField()),
                ('city', models.CharField(max_length=64)),
                ('town', models.CharField(default='', max_length=120)),
                ('animal', models.CharField(max_length=64)),
                ('quantity', models.CharField(max_length=10)),
                ('time', models.CharField(max_length=80)),
                ('heard', models.CharField(blank=True, max_length=64)),
            ],
        ),
    ]
