# Generated by Django 3.2.3 on 2021-06-21 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders3', '0002_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='coupon',
            field=models.CharField(max_length=10),
        ),
    ]
