# Generated by Django 3.2.3 on 2021-06-21 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders3', '0003_alter_discount_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='coupon',
            field=models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.CASCADE, related_name='coupon', to='orders3.customer'),
        ),
    ]
