# Generated by Django 3.2.3 on 2021-06-21 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders3', '0004_alter_discount_coupon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Discount',
        ),
    ]
