# Generated by Django 3.2.3 on 2021-06-22 04:06

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders3', '0007_alter_discount_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='coupon_id',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupon', to='orders3.customer'),
            preserve_default=False,
        ),
    ]
