# Generated by Django 3.2.3 on 2021-06-22 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders3', '0008_discount_coupon_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='coupon_id',
        ),
    ]
