# Generated by Django 3.2.3 on 2021-06-22 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders3', '0010_discount_cpn_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='cpn_id',
        ),
    ]
