# Generated by Django 3.2.3 on 2021-06-22 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders3', '0011_remove_discount_cpn_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Discount',
        ),
    ]
