# Generated by Django 3.2.3 on 2021-06-22 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders3', '0013_discount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Discount',
        ),
    ]
