# Generated by Django 3.2.3 on 2021-06-22 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders3', '0014_delete_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='coupon',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
