# Generated by Django 3.2.3 on 2021-07-11 11:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders3', '0016_auto_20210622_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='date_order',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
